"""
agent/tools/pr_creator.py
Tool: Creates a detailed Pull Request after auto-fix patches are applied.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agent.state import AgentState

from agent.github_client import GitHubClient

logger = logging.getLogger(__name__)


def build_pr_body(state: "AgentState", patches_result: dict) -> str:
    """
    Construct a rich Markdown PR description from agent state.

    Args:
        state: Current AgentState.
        patches_result: LLM patch result dict (may include 'pr_body').

    Returns:
        Markdown string for the PR body.
    """
    # Prefer the LLM-generated PR body if present
    if patches_result.get("pr_body"):
        llm_body = patches_result["pr_body"]
        # Append our audit section
        audit = _build_audit_section(state)
        return llm_body + "\n\n---\n" + audit

    # Fallback: build our own description
    error_list = "\n".join(
        f"- **[{e.error_type}]** {e.message}"
        + (f" (`{e.file_path}:{e.line_number}`)" if e.file_path else "")
        for e in state.errors
    )

    files_changed = ""
    if state.fix_attempts:
        last = state.fix_attempts[-1]
        files_changed = "\n".join(f"- `{f}`" for f in last.files_changed)

    body = f"""## 🤖 Automated CI/CD Fix

> This PR was generated automatically by the **CI/CD Pipeline Error Analysis Agent**.

---

### 🔍 Problem

**Platform:** `{state.platform}`  
**Root Cause:** {state.root_cause}

#### Detected Errors

{error_list or "_No structured errors extracted._"}

---

### 🛠️ Fix Applied

**Strategy:** {state.fix_strategy}

#### Files Modified

{files_changed or "_See commit diff for changes._"}

---

### ✅ How to Verify

1. Pull this branch locally and run the CI/CD pipeline.
2. Confirm all previously failing jobs now pass.
3. Run the relevant test suite for the modified files.

---

### ⚠️ Disclaimer

This fix was generated by an AI agent. Please review the changes carefully
before merging, especially for security-sensitive files.

{_build_audit_section(state)}
"""
    return body


def _build_audit_section(state: "AgentState") -> str:
    """Return a collapsed audit log section for the PR body."""
    log_lines = "\n".join(state.agent_log[-30:])  # last 30 entries
    return f"""<details>
<summary>🔎 Agent Audit Log</summary>

```
{log_lines}
```

</details>"""


def create_pull_request(
    state: "AgentState",
    gh: GitHubClient,
    patches_result: dict,
    base_branch: str = "main",
) -> "AgentState":
    """
    Open a Pull Request for the auto-fix branch.

    Updates state.pr_url, state.pr_number, and state.pr_created.

    Args:
        state: Current AgentState (branch_name must be set).
        gh: Authenticated GitHubClient.
        patches_result: LLM patch result dict.
        base_branch: Target branch for the PR.

    Returns:
        Updated AgentState.
    """
    pr_title = patches_result.get(
        "pr_title",
        f"fix(cicd): auto-remediate pipeline failure — {state.root_cause[:60]}",
    )
    pr_body = build_pr_body(state, patches_result)

    state.log(f"Creating PR: '{pr_title}' → {base_branch}")

    try:
        pr_number, pr_url = gh.create_pull_request(
            repo_name=state.repo_name,
            title=pr_title,
            body=pr_body,
            head=state.branch_name,
            base=base_branch,
            labels=["automated-fix", "cicd"],
        )
        state.pr_number = pr_number
        state.pr_url = pr_url
        state.pr_created = True
        state.log(f"PR created: #{pr_number} — {pr_url}")
    except Exception as exc:
        logger.error("PR creation failed: %s", exc)
        state.log(f"ERROR: PR creation failed: {exc}")
        state.pr_created = False

    return state
