"""
agent/tools/solution_writer.py
Tool: Generates a rich Markdown fallback solution guide when auto-fix fails.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agent.state import AgentState

from agent.llm import get_llm, build_solution_guide_prompt

logger = logging.getLogger(__name__)


def generate_solution_guide(state: "AgentState") -> "AgentState":
    """
    Generate a detailed, human-readable remediation guide using the LLM.

    This is the fallback path when automated patching and PR creation fail.
    The guide is stored in state.solution_guide.

    Args:
        state: Current AgentState (root_cause and fix_strategy must be set).

    Returns:
        Updated AgentState with solution_guide populated.
    """
    state.log("Generating fallback solution guide")

    errors_text = "\n".join(
        f"- [{e.error_type}] {e.message}"
        + (f"\n  File: {e.file_path}:{e.line_number}" if e.file_path else "")
        + (f"\n  Context:\n    {e.context[:300]}" if e.context else "")
        for e in state.errors
    ) or state.error_summary or "See raw log for details."

    try:
        llm = get_llm(temperature=0.2)
    except Exception as exc:
        logger.error("LLM init failed: %s", exc)
        state.log(f"ERROR initialising LLM: {exc}")
        state.solution_guide = _minimal_guide(state, errors_text)
        return state

    prompt = build_solution_guide_prompt()

    try:
        chain = prompt | llm
        response = chain.invoke({
            "platform": state.platform,
            "repo": state.repo_name,
            "root_cause": state.root_cause,
            "fix_strategy": state.fix_strategy,
            "errors": errors_text,
        })
        state.solution_guide = response.content.strip()
        state.log("Solution guide generated successfully")
    except Exception as exc:
        logger.error("Solution guide generation failed: %s", exc)
        state.log(f"ERROR generating solution guide: {exc}")
        # Provide a minimal built-in guide
        state.solution_guide = _minimal_guide(state, errors_text)

    return state


def _minimal_guide(state: "AgentState", errors_text: str) -> str:
    """Return a minimal solution guide when the LLM is unavailable."""
    attempts_summary = ""
    for att in state.fix_attempts:
        status = "✅ Success" if att.success else "❌ Failed"
        attempts_summary += f"- Attempt {att.attempt_number}: {att.strategy} — {status}\n"

    return f"""# CI/CD Pipeline Error — Remediation Guide

## Platform
`{state.platform}`

## Repository
`{state.repo_name}`

## Root Cause
{state.root_cause or "Could not be determined automatically."}

## Detected Errors
{errors_text}

## Suggested Fix Strategy
{state.fix_strategy or "Manual investigation required."}

## Auto-Fix Attempts
{attempts_summary or "No automated fix was attempted."}

## Next Steps
1. Review the errors listed above carefully.
2. Check the affected files: {', '.join(f'`{f}`' for f in state.affected_files) or 'see log'}.
3. Apply the suggested strategy manually.
4. Run the CI/CD pipeline to verify the fix.
5. If the issue persists, consult your team or open a support ticket.

---
_Generated by the CI/CD Pipeline Error Analysis Agent (fallback mode)._
"""
